variables:
  RESCUE_PROJECT: "linaro/qcomlt/rescue"

build:
  image: debian:stable
  tags: [amd64-runner]
  parallel:
    matrix:
      - MACHINE: [dragonboard410c, dragonboard820c, dragonboard845c, rb1, rb2, rb5]
        TARGET: [aosp, linux]
  script:
    - apt update
    - apt -y install python3
    - python3 ./ptool.py -x $MACHINE/$TARGET/partition.xml -t out
    - find $MACHINE/ -maxdepth 1 -name "*.xml" -exec  cp {} out/ \;
    - echo ${CI_COMMIT_SHA} > out/commit
    - cp $MACHINE/$TARGET/flashall out/
  artifacts:
    paths:
      - out/flashall
      - out/gpt*
      - out/patch*
      - out/rawprogram[0-9].xml
      - out/zeros*
      - out/commit
    name: "gpt-$MACHINE-$TARGET"

trigger_rescue:
  stage: .post
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  trigger:
    project: ${RESCUE_PROJECT}
